import typing as t
from datetime import datetime, timezone
from uuid import UUID, uuid4

from .abstract import AbstractDomainMessage


class DomainCommand(AbstractDomainMessage):
    __reference__: UUID  # Autogenerated command reference, can be restored
    __timestamp__: int   # Autogenerated command created time, can be restored
    ...              # Other data fields

    class Meta:
        is_baseclass: bool  # Base class can't used as command only for make inheritance classes. Isn't inheritable property. By default is False
        domain: str         # Domain name for command. Is inheritable property, and can't be change for inherited classes

